on:
  rss:
    url:
      - https://feedx.net/rss/guanzhi.xml
      - https://www.huangjiwei.com/blog/?feed=rss2
      - https://signal.supchina.com/feed/
      - https://cuphistory.net/feed/
      - https://www.moerats.com/bilibili/rss/?id=3697166795
jobs:
  request:
    name: Make a HTTP Request
    runs-on: ubuntu-latest
    steps:
      - name: Make a HTTP Request
        uses: actionsflow/axios@v1
        with:
          url: https://cubox.pro/c/api/save/3chiugs3kffu6z
          method: POST
          body: |
            {
              "type":"url",
              "content":"${{ on.rss.outputs.link }}", 
              "title": "${{ on.rss.outputs.title }}",
              "folder":"RSS"
            }
